node {
 
  
	
 
 stage('Git-Checkout') {
   git 'https://github.com/devops311/user-project-application.git'
  }
    
 def project_path="application-code/code/userproject"
 
 dir(project_path) {
    stage('Maven-Clean') {
   sh label: '', script: 'mvn clean'
  }
    
 stage('Maven-Compile') {
   sh label: '', script: 'mvn compile'
  }
  
   stage('Maven-Package') {
   sh label: '', script: 'mvn package'
  }
	  stage('Maven-Install') {
   sh label: '', script: 'mvn install'
  }
 }
    def project_pathh="application-code"
	 
   dir(project_pathh) {
  stage('Docker-Stage-Deployment') {
   
	  
    sh 'docker build -t user_projectimg:$BUILD_NUMBER . '
   sh ' docker run -d -p 8081:8080  --name user_projectcontainer$BUILD_NUMBER user_projectimg:$BUILD_NUMBER '
    
  }
  
	  
   }
}

